services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
  hotels:
    build:
      context: .
      dockerfile: ./apps/hotels/Dockerfile
      target: development
    command: npm run start:dev hotels
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
