services:
  # hotel-hive:
  #   build:
  #     context: .
  #     dockerfile: ./apps/hotel-hive.services/Dockerfile
  #     target: development
  #   command: npm run start:dev
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env
  #   depends_on:
  #     users:
  #       condition: service_healthy
  #     reservations:
  #       condition: service_healthy
  #     hotels:
  #       condition: service_healthy
  #     payments:
  #       condition: service_healthy
  # volumes:
  #   - .:/usr/src/app
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    ports:
      - '3001:3001'
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/app
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '3002:3002'
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/app
  hotels:
    build:
      context: .
      dockerfile: ./apps/hotels/Dockerfile
      target: development
    command: npm run start:dev hotels
    ports:
      - '3003:3003'
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    ports:
      - '3004:3004'
    env_file:
      - .env
    # volumes:
    #   - .:/usr/src/app
  mongo:
    image: mongo
