apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotels
  name: hotels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
        - image: hotel-hive.services/hotels/production
          name: production
